Deltares/imod_coupler

.github/workflows/CI.yml, examples/dummy_example.py, tests/test_dummy.py
Also adds a dummy test and a dummy example
=> Add coverage and pytest to CI

imod_coupler/metamod.py
=> Adding call to the MetaSWAP finalize time step method.

imod_coupler/metamod.py
https://issuetracker.deltares.nl/browse/IMOD6-241
=> Fixing the read map function for the specific mod2svat.inp format

imod_coupler/__main__.py, imod_coupler/metamod.py
Most of the work is done in amipy as suggested by @rleander 
For details see:
https://github.com/Deltares/amipy/pull/20
https://github.com/Deltares/amipy/pull/22
=> Metaswap deps can be added when used as python lib

imod_coupler/__main__.py, imod_coupler/metamod.py
Please review my renaming of the do_time_step method
=> Renaming do time step

imod_coupler/__init__.py, imod_coupler/__main__.py, imod_coupler/metamod.py
- Implement proper log support
- Replace exit with Exceptions
- Refactor __init__
Please see https://issuetracker.deltares.nl/browse/IMOD6-255
=> Refactor imod_coupler

imod_coupler/__main__.py, imod_coupler/metamod.py
Julian, please review only the commit in this branch, the other branch can be removed (refactor_metamod_class)
=> Refactor MetaMod as a separate new class instead of inheriting wrapper

imod_coupler/__main__.py, imod_coupler/metamod.py
Please see https://issuetracker.deltares.nl/browse/IMOD6-273
=> Add timing support and refactor argparse

LICENSE
This was decided after consulting Martijn Russcher, as well as Arthur Baart.
=> Add LPGL licence

imod_coupler/__main__.py, imod_coupler/metamod.py
Please see https://issuetracker.deltares.nl/browse/IMOD6-302
=> Documentation and slight refactoring

imod_coupler/metamod.py, imod_coupler/utils.py
I have rhe new exchange routine working using sparse matrices, tested it quantitatively by comparing with the arrays after exchange in the old and new method and ran flak8. Please review my branch
=> Sparse exchange

.github/workflows/build_executable.yml
With this commit, for every push on master and on a PR,
a self-contained executable will be produced
Please see https://issuetracker.deltares.nl/browse/IMOD6-269
=> Add github actions to build executable

imod_coupler/__main__.py, imod_coupler/config.py, imod_coupler/errors.py, imod_coupler/kernel.py, imod_coupler/metamod.py, imod_coupler/utils.py, setup.py
Please see https://issuetracker.deltares.nl/browse/IMOD6-348
=> Setup config class based on toml

.gitattributes, README.md, TECHNICAL.md, figures/MF6BMI_coupling.png
Please continue from here @JoerivanEngelen 
The Jira issue can be found here https://issuetracker.deltares.nl/browse/IMOD6-39
=> Extend README and add technical reference

imod_coupler/metamod.py, imod_coupler/utils.py
Add a mask array to the mapping facility to deal with mappings that are not 'onto'
Add some documentation to the mapping file reader
relates to https://issuetracker.deltares.nl/browse/IMOD6-388
=> Imod6 388 storage

TECHNICAL.md, imod_coupler/metamod.py
This serves partly as a working document at the moment, but will be the manual after we fixed the coupling of wells.
=> Extending the Technical reference with a description of the files required for coupling

imod_coupler/metamod.py
- add proper tag for MSW-RCH variable
=> - made sprinkling optional

imod_coupler/metamod.py
=> Bug fix: conversion from sc1 to ss should be based on cell volume

docs/_templates/navbar.html
This will generate a "hamburger menu" when the browser window becomes too narrow for all entries.
=> Add a navbar-toggler to layout

tests/test_metamod.py
Added a testcase and test for storage coefficient.
=> Add storage coefficient test

docs/technical.rst
=> Corrected explanation storage and updated requirements

imod_coupler/utils.py
Some minor improvements to the ``create_mapping`` function.
Only merge after unit tests for ``create_mapping`` function are created.
=> Minor improvements to create_mapping

imod_coupler/drivers/dfm_metamod/mf6_wrapper.py
function to add correction-term to the mf6 wel-package
=> IMOD-946: add

environment.yml
That keeps the testbench green for now
=> Fix imod Python commit

imod_coupler/drivers/dfm_metamod/config.py, imod_coupler/drivers/dfm_metamod/dfm_metamod.py, imod_coupler/drivers/dfm_metamod/mapping_functions.py, tests/test_mapping_example.py
The  imod6_946_correction_flux  had been split off from the lumricus branch a long time ago, and both merge and rebase proved problematic. So I split off a new branch from lumbricus, and I moved the relevant changes into it.
=> migrated the changes in imod6_946_correction_flux into this branch

.github/workflows/docs.yml, README.md, environment.yml, imod_coupler/drivers/dfm_metamod/dfm_metamod.py, imod_coupler/drivers/dfm_metamod/mapping_functions.py, imod_coupler/drivers/metamod/metamod.py, setup.cfg, tests/dfm_test_initialization.py, tests/fixtures/fixture_model.py, tests/test_config_cases.py, tests/test_dfm_metamod_cases.py, tests/test_dfm_wrapper.py, tests/test_mapping.py, tests/test_mapping_example.py, tests/test_metamod.py, tests/test_metamod_cases.py, tests/test_mf6_wrapper.py, tests/test_modstrip.py, tests/test_wrappers.py
-adapted river model to pass imod-python validation
=> -merged from main

imod_coupler/drivers/dfm_metamod/dfm_metamod_model.py, tests/data/t_model/imod_coupler.toml, tests/test_dfm_metamod_cases.py, tests/test_dfm_metamod_model.py
added path to output configuration file to toml, and created a test
=> created test for dfm_metamod_model output

environment.yml, imod_coupler/__main__.py, imod_coupler/config.py, imod_coupler/drivers/driver.py, imod_coupler/drivers/ribametamod/config.py, imod_coupler/drivers/ribametamod/ribametamod.py, tests/fixtures/fixture_paths.py, tests/test_ribametamod.py, tests/test_ribametamod_cases.py
This is mostly a copy of `MetaMod` at the moment.
Depends on https://gitlab.com/deltares/imod/imod-python/-/merge_requests/217
=> Add minimal version of `RibaMetaMod`

.github/workflows/lint.yml, imod_coupler/kernelwrappers/mf6_wrapper.py, tests/test_mf6_wrapper.py
Fix until [MODFLOW 6 commit 135e1a65bcb7054b0df875df755c803ba5651632](https://github.com/MODFLOW-USGS/modflow6/commit/135e1a65bcb7054b0df875df755c803ba5651632)
=> Adapt modflow6 changes

imod_coupler/drivers/driver.py, imod_coupler/drivers/metamod/metamod.py, imod_coupler/drivers/ribametamod/config.py, imod_coupler/drivers/ribametamod/ribametamod.py, pre-processing/primod/__init__.py, pre-processing/primod/metamod/mappingbase.py, pre-processing/primod/ribametamod/__init__.py, pre-processing/primod/ribametamod/ribametamod.py, tests/test_ribametamod.py, tests/test_ribametamod_cases.py
=> Create RibaMetaMod as a copy of RibaMod

imod_coupler/drivers/ribamod/ribamod.py, imod_coupler/kernelwrappers/mf6_wrapper.py, tests/fixtures/fixture_modflow.py, tests/fixtures/fixture_ribasim.py, tests/test_config.py, tests/test_metamod.py, tests/test_mf6_wrapper.py, tests/test_ribamod.py, tests/test_ribamod_cases.py
The glob in the ribamod tests was wrong, leading to all of them being skipped. In the meantime, they broke, so they need to be fixed now.
=> Fix ribamod tests

.gitignore, pixi.toml, tests/fixtures/fixture_ribasim.py
geometry_from_connectivity is now a method
=> Adapt to changed Ribasim Python API

.github/workflows/lint.yml, imod_coupler/drivers/metamod/config.py, imod_coupler/drivers/ribametamod/config.py, imod_coupler/kernelwrappers/mf6_wrapper.py, pixi.toml
It does not seem to be needed anymore
=> Remove pydantic config `arbitrary_types_allowed`

imod_coupler/drivers/metamod/config.py, imod_coupler/drivers/metamod/metamod.py, imod_coupler/drivers/ribametamod/config.py, imod_coupler/drivers/ribametamod/mapping.py, imod_coupler/drivers/ribametamod/ribametamod.py, imod_coupler/drivers/ribamod/config.py, imod_coupler/drivers/ribamod/ribamod.py, imod_coupler/kernelwrappers/mf6_wrapper.py, imod_coupler/kernelwrappers/msw_wrapper.py, imod_coupler/logging/exchange_collector.py, imod_coupler/utils.py, pixi.toml, pre-processing/primod/metamod/mappingbase.py, pre-processing/primod/metamod/metamod.py, pre-processing/primod/ribametamod/ribametamod.py, pre-processing/primod/ribamod/ribamod.py, pyproject.toml, tests/fixtures/fixture_modflow.py, tests/test_config.py, tests/test_general.py, tests/test_metamod.py, tests/test_metamod_cases.py, tests/test_scripts/mf6_water_balance/MF6_wbal_listing.py, tests/test_scripts/mf6_water_balance/combine.py, tests/test_utilities.py, tests/test_waterbalance_script.py
This is is mostly to enforce modern Python syntax
=> Add more ruff rules

pre-processing/pyproject.toml, pyproject.toml
That way IDEs like vscode work with editable installs
=> Move to hatchling as backend

imod_coupler/drivers/ribamod/ribamod.py, pre-processing/primod/ribamod/ribamod.py, tests/fixtures/fixture_modflow.py, tests/test_ribamod.py, tests/test_ribamod_cases.py
Pretty minimal, but maybe you reckon there's better naming possible.
This requires the changes of: https://github.com/Deltares/Ribasim/pull/1028
I will add a test based on the backwater model.
Will close:
https://github.com/Deltares/Ribasim/issues/998
https://github.com/Deltares/Ribasim/issues/999
=> Do not overwrite the drainage and infiltration values of uncoupled basins

pre-processing/primod/ribamod/ribamod.py, tests/test_primod/test_preprocessing_ribamod.py
Fixes https://github.com/Deltares/Ribasim/issues/1073
=> Set drainage and infiltration to NA for basins coupled to MODFLOW

imod_coupler/drivers/ribamod/ribamod.py, imod_coupler/kernelwrappers/mf6_wrapper.py, tests/test_mf6_wrapper.py
Functional change: make sure to call update_bottom_minimum!
Refactoring: define water_level property on Drainage and River. Define exchange_rib2mod and exchange_mod2rib.
=> Call update_bottom_minimum and refactor a little

imod_coupler/drivers/ribametamod/ribametamod.py, tests/test_primod/test_preprocessing_ribamod.py, tests/test_ribametamod.py, tests/test_ribamod.py, tests/test_ribamod_cases.py
See https://github.com/Deltares/Ribasim/pull/1148
=> Adapt to change in Ribasim

imod_coupler/drivers/ribamod/ribamod.py, tests/fixtures/fixture_ribasim.py, tests/test_ribamod.py
name change in ribamod because of change in ribasim api
=> changes in ribamod for changed names in Ribasim API

pre-processing/primod/ribamod/exchange_creator.py
I was running into input with a time axis on the drainage and river conductance levels (summer / winter). Turns out I didn't call the _time_invariant helper at the right place, so I would be collecting indices from transient data. With this fix, Joachim's model is running.
=> Deal with potential time axis in conductance

tests/fixtures/fixture_modflow.py, tests/fixtures/fixture_ribametamod.py, tests/fixtures/fixture_ribasim.py, tests/test_imod_coupler/test_metamod_cases.py, tests/test_imod_coupler/test_ribametamod.py, tests/test_imod_coupler/test_ribametamod_cases.py, tests/test_imod_coupler/test_ribamod.py, tests/test_imod_coupler/test_ribamod_cases.py
We need this to make the ribamod tests run again
=> Fix tests mismatch riba mod coordinates

imod_coupler/drivers/ribametamod/exchange.py, imod_coupler/drivers/ribametamod/ribametamod.py
replace the dummy values in the realised infiltration by the real values obtained from the integrated drainage and infiltration from Ribasim
=> Ribasim1164 mf6 correction

imod_coupler/drivers/ribametamod/ribametamod.py
realized and realised mixed up here
=> fixed typo in var name

.teamcity/IMODCollector/buildTypes/IMODCollector_X64development.kt, .teamcity/IMODCollector/buildTypes/IMODCollector_X64developmentLnx64.kt, .teamcity/Primod/buildTypes/Primod_TestPrimodWin64.kt, .teamcity/_Self/buildTypes/TestbenchCouplerWin64_2.kt, pixi.toml, pre-processing/primod/driver_coupling/util.py, tests/test_imod_coupler/test_ribametamod_cases.py, tests/test_imod_coupler/test_ribamod_cases.py, tests/test_primod/test_preprocessing_ribamod.py
run extra update git dependencies pixi task to take into account unpu……blished ribasim python changes
=> update ribasim python before building coupler to have the latest stuff

scripts/download_imod_collector.py, tests/test_imod_coupler/test_ribamod.py
update to Infiltration and drainage budget output from Ribasim
=> update failing backwater test

imod_coupler/drivers/ribametamod/ribametamod.py
Merge when https://github.com/Deltares/Ribasim/pull/1852 is merged.
=> Rename Ribasim BMI variables
