imod_coupler/metamod.py
- SC1 should be used, not SC2
- there is a reset flag that should be set whenever the value changes to trigger
modflow side effects
- Recharge is the first column in the BOUND array, which has rank 2!
- there's no head exchange into metaswap inside the initialize, BUT,
there should be one before the iteration loop
- array assignment results causes the member (e.g. self.mf6_head) to no
longer point to the proper array inside the Fortran kernel, replaced this
by broadcast
This addresses issue IMOD6-271, which should be tested again.
(Paired with RL)
=> Crucial fixes to the metamod.py script:

imod_coupler/__main__.py, imod_coupler/config.py, imod_coupler/metamod.py
After a talk with Joeri, I try to to finalize the command line interface with this PR.
New options can be added, but existing ones should not be modified anymore.
This PR includes
- timing and log_level is moved to CLI again
- config_path is a positional parameter now
- refactor timing (otherwise it would stop working
when we add additional kernels)
Instead of
```
imodc --config-path=/path/to/imod_coupler.toml
```
it is now
```
imodc /path/to/imod_coupler.toml
```
The necessary changes are already done in the testbench, so as soon as this is merged it should work again.
The current design is:
- user- (or developer-) specific settings via the CLI
- model settings via the config file (which can be overriden via env variables)
If you have any last design suggestions, please free to add them …
=> Finalize CLI interface

imod_coupler/metamod.py
Changed the sign of the `qmodf` flow between MF6 and MetaSWAP. 
I implemented this incorrectly before, to account for errors that were apparently created by the diverging heads. 
The head divergence issue is now fixed in the MetaSWAP.dll and it seems that multiplying `qmodf` with -1.0 created an erronous coupling and should therefore be reverted.
=> Fix flow direction

imod_coupler/metamod.py
before exchanging with modflow, no need to trigger the update routine inside modflow.
https://issuetracker.deltares.nl/browse/IMOD6-384
=> metaswap properly converts the storage coefficient

imod_coupler/drivers/metamod/metamod.py, imod_coupler/utils.py
There are some issues running iMOD Coupler on Python 3.8, these modifications make it work.
I'm not sure if the ``from __future__ import annotations`` breaks when useing Python 3.10.
=> Make iMOD Coupler compatible with Python 3.8

tests/test_metamod.py
I added three cases where either the modflow 6 or metaswap failures should fail.
I couldn't come up with a case where metaswap did not converge, as even:
``iter_outer =  2 : [Hgwmsw - Hgwmodf] (svat=      1)=-99.99565 m``
was good enough for metaswap,
=> Add failure cases and specific test to test if we catch failures.

tests/fixtures/fixture_model.py
Minor thing, but python 3.8 requires objects from the ``typing`` module for its type annotations.
=> Import from typing module, to make the code compatible with python 3.8

tests/test_metamod_cases.py
See https://github.com/MODFLOW-USGS/modflow6/pull/1141 by @mjr-deltares 
@luitjansl You will probably want to merge this change into the lumbricus branch
=> No convergence in MODFLOW doesn't result in an error anymore

environment.yml, tests/fixtures/fixture_model.py, tests/test_config_cases.py, tests/test_mapping.py, tests/test_metamod.py, tests/test_metamod_cases.py, tests/test_modstrip.py
Fixes https://issuetracker.deltares.nl/browse/IMOD6-985, and should nullify the issue fixed in this PR https://github.com/Deltares/imod_coupler/pull/121
The latest iMOD Python release has added model input validation for Modflow 6. 
I took a shortcut in the ``msw_fixture``, for which I incorrectly provided the ``bottom`` in the MF6 discretization as a scalar.
This fixes this.
Furthermore, in one test, we want Modflow 6 to fail, not iMOD Python. So in this case I had to turn off the validation. To do this, I had to add a kwarg to a method in iMOD Python. So to have working tests, it is neatest to have a new iMOD Python release. 
For now, I updated the ``environment.yml``, so we can test.
If the iMOD Python pipeline runs succesfully, I can release a new iMOD Python version: …
=> Imod 985 mf6 validation

imod_coupler/drivers/metamod/metamod.py
msw_time only exist within the MetaMod-driver and is not used by kernels.
=> deleted variable msw_time

pyproject.toml
The asterisk is necessary to find submodules
=> Fix `tool.setuptools.packages.find`

pixi.toml, tests/test_ribametamod.py, tests/test_ribamod.py
Otherwise I've got the following error on TeamCity:
```
InitError(mod=:WindowsTimeZoneIDs, error=Base.IOError(msg="unlink("D:\\buildAgent\\work\\c463fd4bc9a9a18\\imod_collector_devel\\ribasim\\share\\julia\\scratchspaces\\f269a46b-ccf7-5d73-abea-4c690281aa53\\build\\local\\windowsZones.xml"): resource busy or locked (EBUSY)", code=-4082)
```
=> Enforce that Ribasim tests run on the same worker

pre-processing/primod/ribamod/ribamod.py, tests/fixtures/fixture_modflow.py, tests/test_primod/test_preprocessing_ribamod.py, tests/test_ribamod.py
Requires https://github.com/Deltares/Ribasim/pull/1080
=> Check time of Ribasim and MODFLOW6 model before coupling

pre-processing/primod/mapping/rch_svat_mapping.py, tests/fixtures/fixture_modflow.py, tests/test_mapping.py, tests/test_mapping_cases.py
This PR fixes issue #262, as well as adds some unit tests to verify that most common cases in which recharge can be provided work.
- 2D grid (y, x) with ``layer`` coord (succeeds)
- 3D grid with layer dimension, length 1 (succeeds)
- 3D grid with multiple layers (fails)
- 2D transient grid (fails)
I placed the new tests in the ``tests/test_mapping.py``, but I noticed there is a ``imod_coupler/mapping`` namespace, as well as a ``primod/mapping`` namespace. I was a bit in doubt whether mixing these in ``tests/test_mapping.py`` is a good idea. If you have ideas for a better location to put these tests, let me know.
=> Issue #262 primod rchsvatmapping layer dim

imod_coupler/drivers/ribametamod/ribametamod.py
please merge in main, just changed names in accordance with recent changes in Riba
=> name changes riba variables in get_value_ptr statements

.github/workflows/lint.yml
Let's revert this when https://github.com/prefix-dev/pixi/pull/951 is merged and released
=> Pin pixi for now

imod_coupler/drivers/metamod/config.py, imod_coupler/drivers/metamod/metamod.py, imod_coupler/drivers/ribametamod/config.py, imod_coupler/drivers/ribametamod/mapping.py, imod_coupler/drivers/ribametamod/ribametamod.py, pre-processing/primod/driver_coupling/metamod.py, pre-processing/primod/ribametamod.py, tests/test_imod_coupler/test_config.py, tests/test_imod_coupler/test_modstrip.py, tests/test_primod/test_preprocessing_metamod.py
Base it off whether a map file is provided. Make names consistent between MetaMod and RibaMetaMod.
=> Simplify enable_sprinkling

.teamcity/iMOD6_IMOD6collectorDaily/project-config.xml
This commit fixes a failing build configuration.
The configuration was failing because it was lacking a unique uuid
=> Fix failing teamcity configuration

.teamcity/Primod/buildTypes/Primod_TestPrimodWin64.kt, pixi.toml, pre-processing/primod/driver_coupling/util.py, tests/test_primod/test_preprocessing_ribamod.py
Basin definition for Two basin model as copy of model schematization and add node_id column. Update Nullify test with new index name
=> Fix Primod tests

pre-processing/primod/driver_coupling/ribameta.py, pre-processing/primod/driver_coupling/ribamod.py, pre-processing/primod/driver_coupling/util.py, pre-processing/primod/mapping/node_basin_mapping.py, tests/test_primod/test_ribamod_exchange_creator.py
The driver_couplings related to Ribasim can now contain grid-based basin and water user definition. This gives the optional ```xr.Dataset``` or ```xr.DataArray```.
- ```xr.Dataset``` in ```primod.driver_coupling.RibaModDriverCoupling```:  per mf-package  a basin definition data variable
```xr.DataArray```  in ```primod.driver_coupling.RibaMetaDriverCoupling```: per (single) basin definition and (single) water user definition.
In the ```primod.driver_coupling.ActiveNodeBasinMapping``` an optional subsetting is possible to deal with stacked subgrid points. Subsetting is done via the optional ‘meta_label’ column in the subgrid.df
=> Allow grid based basin and water user definitions and facilitate subsetting of subgrid-df

imod_coupler/drivers/ribametamod/ribametamod.py
This seems to match the signature better.
https://github.com/Deltares/imod_coupler/blob/162db85368122e9e03c319a96a51ee9bf1d75789/imod_coupler/drivers/ribametamod/exchange.py#L186
=> Pass metaswap timestep to update_ribasim

pixi.lock, pixi.toml, pre-processing/primod/driver_coupling/ribameta.py, pre-processing/primod/driver_coupling/ribamod.py, pre-processing/primod/mapping/wel_svat_mapping.py, tests/fixtures/common.py, tests/fixtures/fixture_metaswap.py, tests/fixtures/fixture_ribametamod.py, tests/test_imod_coupler/test_metamod.py, tests/test_primod/test_wel_svat_mapping.py
Closes #344, this is the first task to update ``primod`` for the iMOD Python refactor.
Plans are layed out in #342. In this first task, I changed the use of the deprecated ``WellDisStructured`` object, to the Mf6Wel object, which is a direct translation of MODFLOW 6's cellids to a file. As this iMOD Python refactor is still work in progress, I temporarily introduce a install-imod task, which pip installs imod from a git branch, instead of a release on conda-forge. After I have accomplished part 2 of the refactors, I'll make an iMOD Python release, and this can be reverted back.
It does the following things:
- Temporarily introduce a install-imod task, which install imod from a git branch
- Use the ``Mf6Wel`` object instead of the ``WellDisStructured`` object
- I had to drop an unused …
=> Issue #344 part1 imod refactor primod update

pixi.lock, pixi.toml, pre-processing/primod/driver_coupling/ribameta.py, pre-processing/primod/driver_coupling/ribamod.py, pre-processing/primod/mapping/wel_svat_mapping.py, tests/fixtures/common.py, tests/fixtures/fixture_metaswap.py, tests/fixtures/fixture_ribametamod.py, tests/test_imod_coupler/test_metamod.py, tests/test_primod/test_wel_svat_mapping.py
Woops, accidentily did the wrong merge. Reverts Deltares/imod_coupler#346
=> Revert "Issue #344 part1 imod refactor primod update"

pixi.lock, pixi.toml, pre-processing/primod/driver_coupling/metamod.py, pre-processing/primod/driver_coupling/ribameta.py, pre-processing/primod/driver_coupling/ribamod.py, pre-processing/primod/mapping/wel_svat_mapping.py, pre-processing/primod/metamod.py, pre-processing/primod/model_mixin.py, pre-processing/primod/ribametamod.py, tests/fixtures/common.py, tests/fixtures/fixture_metaswap.py, tests/fixtures/fixture_modflow.py, tests/fixtures/fixture_ribametamod.py, tests/test_imod_coupler/test_metamod.py, tests/test_imod_coupler/test_ribametamod_cases.py, tests/test_primod/test_mixin.py, tests/test_primod/test_wel_svat_mapping.py
Fixes #342
This PR merges the refactoring branch of MetaSWAP to main. You reviewed this work earlier.
The extra fixes I made with respect to #351 only are in the pixi.toml. What I did:
- pin imod >=0.18.0
- pin pandas >2.0
- Add pandera
In #351, one test job for python 3.10 broke. This was because, pandas 2.0 is required for the ribasim test models, and for some reason, the installed pandas version was set back to 1.5 in the python 3.10 environment. I therefore forced pandas >2.0 in the ``pixi.toml``. 
Furthermore, I added pandera, as this was still missing, whereas it is quite essential in our dev environment, as ribasim python is built on top of it.
=> Issue #342 imod refactor primod update
